spring:
  application:
    name: htbs
  security:
    user:
      name: user
      password: 1234

  # 1. Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/htbs
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 2. JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update    # 개발 끝나고 validate로 변경
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  # 3. Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379

  # 4. MVC Path Matcher
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# 5. Logging Level
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

# 6. Swagger Config
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operations-sorter: method

# 7. Jaegger Config
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      enabled: false
#      endpoint: http://localhost:4318/v1/traces

# 8. jwt
jwt:
  secret: bXktYXdlc29tZS1odGJzLXNlY3JldC1rZXktZm9yLWp3dC1wcm92aWRlci1wb3J0Zm9saW8=
  access-expiration: 1800000  # 30분 (1000 * 60 * 30)
  refresh-expiration: 1209600000 # 14일 (1000 * 60 * 60 * 24 * 14)